// The site's icons are Lucide (https://lucide.dev, ISC): this picks the ones GridStudio uses from
// @iconify-json/lucide and writes scripts/icons.mjs, which the editor (scripts/app.mjs) and the
// React pages (src/Icon.jsx) share. Each shape keeps Lucide's own stroke attributes, so the icons
// look the same everywhere whatever a page's CSS says about strokes.
//   node scripts/make-icons.mjs   (after changing ICON_NAMES)
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const lucide = JSON.parse(readFileSync(require.resolve('@iconify-json/lucide/icons.json'), 'utf8'));
// Our name → Lucide's.
const ICON_NAMES = {
  // Pages and files
  studio: 'layout-grid', grid: 'layout-grid', heroes: 'layout-grid', workshop: 'compass', groupPlus: 'grid-2x2-plus',
  archive: 'archive', copy: 'copy', edit: 'pencil', trash: 'trash-2', search: 'search', import: 'file-down', export: 'share',
  download: 'download', upload: 'upload', external: 'external-link', expand: 'maximize', telegram: 'send', bell: 'bell',
  heart: 'heart', flag: 'flag', brush: 'paintbrush', font: 'type', book: 'book-open', alert: 'circle-alert', help: 'circle-help',
  art: 'image', image: 'image', layers: 'layers', shield: 'shield-check', sparkle: 'sparkles', sliders: 'sliders-horizontal',
  // Actions and arrows
  plus: 'plus', minus: 'minus', close: 'x', check: 'check', arrow: 'arrow-right', back: 'arrow-left',
  chevron: 'chevron-down', chevronRight: 'chevron-right', chevronLeft: 'chevron-left', chevronUp: 'chevron-up',
  eye: 'eye', eyeOff: 'eye-off', lock: 'lock', unlock: 'lock-open', pin: 'pin',
  // Editor tools
  cursor: 'mouse-pointer-2', hand: 'hand', lasso: 'lasso', pen: 'brush', text: 'type', eyedropper: 'pipette', rect: 'square',
  eraser: 'eraser', undo: 'undo-2', redo: 'redo-2', gridLines: 'grid-3x3', magnet: 'magnet', fit: 'scan',
  rotate: 'rotate-cw', rotateHandle: 'rotate-ccw', flip: 'flip-horizontal-2', flipVertical: 'flip-vertical-2',
  labelsHide: 'panel-left-close', labelsShow: 'panel-left-open',
  align: 'align-center-vertical', alignLeft: 'align-start-vertical', alignHCenter: 'align-center-vertical', alignRight: 'align-end-vertical',
  alignTop: 'align-start-horizontal', alignVMiddle: 'align-center-horizontal', alignBottom: 'align-end-horizontal',
  distributeX: 'align-horizontal-distribute-center', distributeY: 'align-vertical-distribute-center',
};
const body = (name) => {
  const icon = lucide.icons[name] || lucide.icons[lucide.aliases?.[name]?.parent];
  if (!icon) throw new Error(`Lucide has no «${name}»`);
  if ((icon.width || lucide.width || 24) !== 24 || (icon.height || lucide.height || 24) !== 24) throw new Error(`«${name}» is not 24 × 24`);
  return icon.body;
};
const icons = Object.fromEntries(Object.entries(ICON_NAMES).map(([ours, theirs]) => [ours, body(theirs)]));
writeFileSync(new URL('./icons.mjs', import.meta.url), `// Generated by scripts/make-icons.mjs from Lucide (ISC, https://lucide.dev). Do not edit.
export const ICONS = ${JSON.stringify(icons, null, 1).replace(/\n\s*/g, '\n  ').replace(/\n  }$/, '\n}')};
// An icon as markup, for the editor's imperative DOM; React pages use src/Icon.jsx.
export const iconSVG = (name, className = '') => \`<svg\${className ? \` class="\${className}"\` : ''} viewBox="0 0 24 24" aria-hidden="true">\${ICONS[name] || ICONS.rect}</svg>\`;
`);
console.log(`scripts/icons.mjs: ${Object.keys(icons).length} icons`);
